name: Build macOS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  Qt_minor_version: 5.15
  Qt_patch_version: 5.15.15
  BUILD_TYPE: Release
  
jobs:
  build:
    runs-on: macos-12
    steps:        
      - name: Download Qt ${{ env.Qt_patch_version }}
        run: |
          wget https://download.qt.io/archive/qt/${{ env.Qt_minor_version }}/${{ env.Qt_patch_version }}/single/qt-everywhere-opensource-src-${{ env.Qt_patch_version }}.tar.xz
          
      - name: Extract Qt ${{ env.Qt_patch_version }}
        run: |
          tar -xf qt-everywhere-opensource-src-${{ env.Qt_patch_version }}.tar.xz
          rm -f qt-everywhere-opensource-src-${{ env.Qt_patch_version }}.tar.xz

      - name: Install Ninja
        run: |
          brew install ninja
          
      - name: Configure Qt ${{ env.Qt_patch_version }}
        working-directory: qt-everywhere-src-${{ env.Qt_patch_version }}
        run: |
          ./configure \
          -opensource \
          -confirm-license \
          -release \
          -static \
          -platform macx-clang \
          -nomake examples \
          -nomake tests \
          -no-compile-examples \
          -no-dbus \
          -no-accessibility \
          -qt-doubleconversion \
          -no-icu \
          -no-schannel \
          -no-securetransport \
          -no-cups \
          -no-fontconfig \
          -no-harfbuzz \
          -no-gtk \
          -no-opengl \
          -no-direct2d \
          -no-eglfs \
          -no-ico \
          -no-sql-db2 \
          -no-sql-ibase \
          -no-sql-mysql \
          -no-sql-oci \
          -no-sql-odbc \
          -no-sql-psql \
          -no-sql-sqlite \
          -no-sql-sqlite2 \
          -no-sql-tds \
          -no-tiff \
          -no-webp \
          -no-feature-sqlmodel \
          -no-feature-testlib_selfcover \
          -no-feature-textmarkdownreader \
          -no-feature-textmarkdownwriter \
          -no-feature-textodfwriter \
          -skip qt3d \
          -skip qtactiveqt \
          -skip qtandroidextras \
          -skip qtcanvas3d \
          -skip qtcharts \
          -skip qtconnectivity \
          -skip qtdatavis3d \
          -skip qtdeclarative \
          -skip qtdoc \
          -skip qtfeedback \
          -skip qtgamepad \
          -skip qtgraphicaleffects \
          -skip qtlocation \
          -skip qtlottie \
          -skip qtmacextras \
          -skip qtmultimedia \
          -skip qtnetworkauth \
          -skip qtpim \
          -skip qtpurchasing \
          -skip qtqa \
          -skip qtquick3d \
          -skip qtquickcontrols \
          -skip qtquickcontrols2 \
          -skip qtquicktimeline \
          -skip qtremoteobjects \
          -skip qtrepotools \
          -skip qtscript \
          -skip qtscxml \
          -skip qtsensors \
          -skip qtserialbus \
          -skip qtserialport \
          -skip qtspeech \
          -skip qtsystems \
          -skip qttools \
          -skip qttranslations \
          -skip qtwayland \
          -skip qtwebchannel \
          -skip qtwebengine \
          -skip qtwebglplugin \
          -skip qtwebsockets \
          -skip qtwebview \
          -skip qtwinextras \
          -skip qtx11extras \
          -skip qtxmlpatterns
          
      - name: Build Qt ${{ env.Qt_patch_version }}
        working-directory: qt-everywhere-src-${{ env.Qt_patch_version }}
        run: |
          make
          
      - name: Install Qt ${{ env.Qt_patch_version }}
        working-directory: qt-everywhere-src-${{ env.Qt_patch_version }}
        run: |
          make install
          
      - uses: actions/checkout@v4
      - name: Build project
        run: cmake -S . -B build -G "Ninja Multi-Config" && cmake --build build --config ${{ env.BUILD_TYPE }}

      - name: Check Qt location
        run: |
          echo "Check github workspace..."
          ls ${{ github.workspace }}
          echo "Check last location..."
          ls /usr/local/Qt-5.15.15
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: build/${{ env.BUILD_TYPE }}
          if-no-files-found: ignore
          retention-days: 0
